services:
  evalify-ai:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - CHECKPOINT_DB_PATH=/data/comparaciones.db
    volumes:
      - sqlite_data:/data

volumes:
  sqlite_data:
